### PR TITLE
overrrideInactivity adjusted time to get int instead of string

### PR DESCRIPTION
**Pull request by CatboyDark**
no more errors!

### CODE REVIEW

**Review by Kathund — CHANGES_REQUESTED** [review]
If your going to update it. Please update the inactivity command as well

**Comment by CatboyDark** [comment]
grrrr

**Comment by CatboyDark** [comment]
inactivity uses a modal, which i dont think supports int only input?

**Comment by Kathund** [comment]
> inactivity uses a modal, which i dont think supports int only input?

[Use ms then](https://github.com/Wristspasm/Wristspasm-Discord-Bot/blob/master/src/discord/commands/giveawayCreate.js#L65) so we don't need to deal with people not reading and entering 1d and not 1

**Comment by CatboyDark** [comment]
###### (wat dat)

**Comment by Kathund** [comment]
> ###### (wat dat)

[We have used it before](https://github.com/Wristspasm/Wristspasm-Discord-Bot/blob/master/src/discord/commands/giveawayCreate.js#L65) just check that to see how to use it. Tldr converts 5m to 300000 (5m in milliseconds)

**Comment by Kathund** [comment]
Updated in [this](d8852fee50d631d8306b6e3d08118f6d0c6b16f6) commit so it wont error

**Pull request closed without merging**
