### PR TITLE
removed an line to minimize spam and adjusted phrasing :D

### PR DESCRIPTION
**Pull request by CatboyDark**

### CODE REVIEW

**Comment by CatboyDark** [comment]
meow

**Review by Zickles — APPROVED** [review]
lgtm

**Review by Kathund — APPROVED** [review]

**Comment by Kathund** [comment]
@CatboyDark can we get this on main bot

**Comment by CatboyDark** [comment]
> @CatboyDark can we get this on main bot

wdym? is this not the main bot

**Comment by Kathund** [comment]
> > @CatboyDark can we get this on main bot
> 
> wdym? is this not the main bot

this is the main bot for wristspasm. this bot is a fork of duckys main bot were changes go first then get copied into this

https://github.com/DuckySoLucky/hypixel-discord-chat-bridge/

**Comment by CatboyDark** [comment]
oh. sureeeeeee

**Pull request merged**
